{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#| default_exp plane"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#| export\n",
    "from SolidPy.constants.constants import *\n",
    "\n",
    "class Plane:\n",
    "    def __init__(self, swModel, name, refPlane, offsetDistance, distanceUnits):\n",
    "        self.model = swModel\n",
    "        self.name = name\n",
    "        self.refPlane = refPlane\n",
    "        self.offsetDistance = offsetDistance\n",
    "        self.distanceUnits = distanceUnits\n",
    "\n",
    "    def create(self):\n",
    "        # creates a plane after selecting the reference plane given in the function\n",
    "        print(\"Creating plane\")\n",
    "        modelExt = self.model.Extension\n",
    "        # modelExt = self.model.Extension\n",
    "        featureMgr = self.model.FeatureManager\n",
    "        distance = convertUnits(self.offsetDistance, self.distanceUnits)\n",
    "        BoolStatus = modelExt.SelectByID2(\n",
    "            self.refPlane, \"PLANE\", 0, 0, 0, False, 0, arg1, 0\n",
    "        )\n",
    "        # print(BoolStatus)\n",
    "        print(distance < 0)\n",
    "        if distance < 0:\n",
    "            CreatePlane = featureMgr.InsertRefPlane(\n",
    "                swConst.swRefPlaneReferenceConstraint_Distance | swConst.swRefPlaneReferenceConstraint_OptionFlip,\n",
    "                distance,\n",
    "                0,\n",
    "                0,\n",
    "                0,\n",
    "                0,\n",
    "            )\n",
    "        else:\n",
    "            CreatePlane = featureMgr.InsertRefPlane(\n",
    "                swConst.swRefPlaneReferenceConstraint_Distance, distance, 0, 0, 0, 0\n",
    "            )\n",
    "        # print(CreatePlane)\n",
    "        CreatePlane.Name = self.name\n",
    "        self.model.ClearSelection2(True)\n",
    "        return\n",
    "\n",
    "\n",
    "    def edit(self):  # , swModel, refPlane, offsetDistance, distanceUnits):\n",
    "        # edits a plane after selecting the reference plane given in the function\n",
    "        try:\n",
    "            modelExt = self.model.Extension\n",
    "            # modelExt = self.model.Extension\n",
    "            # featureMgr = self.model.FeatureManager\n",
    "            swSelMgr = self.model.SelectionManager\n",
    "            distance = convertUnits(self.offsetDistance, self.distanceUnits)\n",
    "            BoolStatus = modelExt.SelectByID2(self.name, \"PLANE\", 0, 0, 0, False, 0, arg1, 0)\n",
    "            # print(BoolStatus)\n",
    "            Feature = swSelMgr.GetSelectedObject(1)\n",
    "            swRefPlane = Feature.GetDefinition\n",
    "            # swRefPlane.Distance = distance\n",
    "            swRefPlane.AccessSelections(self.model, arg1)\n",
    "            flip = swRefPlane.ReverseDirection  # ReversedReferenceDirection\n",
    "            print(flip)\n",
    "            if distance < 0:\n",
    "                flip = True  # swConst.swRefPlaneReferenceConstraint_OptionFlip\n",
    "            print(flip)\n",
    "            swRefPlane.ReverseDirection = flip  # (swConst.swRefPlaneReference_First)\n",
    "            swRefPlane.Distance = distance\n",
    "            Feature.ModifyDefinition(swRefPlane, self.model, arg1)\n",
    "            self.model.ClearSelection2(True)\n",
    "            # print(BoolStatus)\n",
    "            # CreatePlane = featureMgr.EditRefPlane(swConst.swRefPlaneReferenceConstraint_Distance, distance, 0, 0, 0, 0)\n",
    "            # print(CreatePlane)\n",
    "            # swModel.ClearSelection2(True)\n",
    "        except:\n",
    "            swRefPlane.ReleaseSelectionAccess\n",
    "            print(\"Error editing plane: \" + self.name)\n",
    "        return\n",
    "\n",
    "    def getProperties(self):\n",
    "        try:\n",
    "            # gets the properties of the plane\n",
    "            properties = []  # \"RefPlane\"]\n",
    "            swSelMgr = self.model.SelectionManager\n",
    "            print(\"Getting properties of plane: \" + self.name)\n",
    "            BoolStatus = self.model.Extension.SelectByID2(\n",
    "                self.name, \"PLANE\", 0, 0, 0, False, 0, arg1, 0\n",
    "            )\n",
    "            print(str(BoolStatus))\n",
    "            if BoolStatus == False:\n",
    "                print(\"Error selecting plane: \" + self.name)\n",
    "                return\n",
    "            Feature = swSelMgr.GetSelectedObject6(1, 0)\n",
    "            print(str(Feature))\n",
    "            swRefPlane = Feature.GetDefinition\n",
    "            swRefPlane.AccessSelections(self.model, arg1)\n",
    "            # if swRefPlane.Selections != None:\n",
    "            print(str(swRefPlane.Selections))\n",
    "            try:\n",
    "                properties.append(swRefPlane.Selections[0].Name)\n",
    "            except:\n",
    "                properties.append(swRefPlane.Selections.Name)\n",
    "\n",
    "            properties.append(swRefPlane.Distance * 1000)\n",
    "            # properties.append(swRefPlane.DistanceType)\n",
    "            # properties.append(swRefPlane.DistanceUnits)\n",
    "            # properties.append(swRefPlane.PlaneType)\n",
    "            self.refPlane = swRefPlane.Selections[0].Name\n",
    "            self.offsetDistance = swRefPlane.Distance * 1000\n",
    "            # self.distanceUnits = properties[1]\n",
    "            swRefPlane.ReleaseSelectionAccess()  # (self.model)\n",
    "            return properties\n",
    "        except:\n",
    "            print(\"Error getting properties of plane: \" + self.name)\n",
    "            swRefPlane.ReleaseSelectionAccess()  # (self.model)\n",
    "            return\n",
    "        \n",
    "\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 2
}
