{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Solidworks API - Working Version\n",
    "Simple API - use template files and save copies + update dimensions to/from CSV file. \n",
    "\n",
    "Bootstrap from a very minimal functionality, limiting the scope as much as possible - even if designing is a PITA."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import csv\n",
    "import time\n",
    "from dataclasses import dataclass\n",
    "\n",
    "import pandas\n",
    "import pythoncom\n",
    "import win32com.client\n",
    "from win32com.client import Dispatch, gencache\n",
    "import SW_API_Functions as SWapi\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Variables\n",
    "SW_TEMPLATE_PATH = os.getenv(\"SW_TEMPLATE_PATH\")\n",
    "SW_TEMPLATE_NAME = os.getenv(\"SW_TEMPLATE_NAME\")\n",
    "SW_TEMPLATE = os.path.join(SW_TEMPLATE_PATH, SW_TEMPLATE_NAME)"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Init Solidworks\n",
    "A class representing a Solidworks session."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Solidworks Class:\n",
    "@dataclass\n",
    "class Solidworks:\n",
    "    def __post_init__(self):\n",
    "        self.instance = win32com.client.Dispatch(\"SldWorks.Application\")\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Solidworks COM Objects\n",
    "Classes representing Solidworks COM objects. Model, part, sketch, etc."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Model:\n",
    "    def __init__(self, fileName=\"ActiveDoc\", fileLocation=\"\"):  # -> None:\n",
    "        if fileName == \"ActiveDoc\":\n",
    "            self.session = SWapi.win32com.client.Dispatch(\"SldWorks.Application\")\n",
    "            self.name = self.session.ActiveDoc.GetTitle\n",
    "            self.templateLoc = fileLocation + \"\\\\\" + self.name\n",
    "            isExist = os.path.exists(self.templateLoc)\n",
    "            print(\"templateLoc = \" + self.templateLoc)\n",
    "            print(self.templateLoc)\n",
    "            if not isExist:\n",
    "                # Create a new directory because it does not exist\n",
    "                os.makedirs(self.templateLoc)\n",
    "            self.model = self.session.ActiveDoc\n",
    "        else:\n",
    "            try:\n",
    "                self.session = SWapi.win32com.client.Dispatch(\"SldWorks.Application\")\n",
    "                self.name = fileName\n",
    "                self.templateLoc = fileLocation + \"\\\\\" + self.name\n",
    "                isExist = os.path.exists(self.templateLoc)\n",
    "                print(\"templateLoc = \" + self.templateLoc)\n",
    "                if not isExist:\n",
    "                    # Create a new directory because it does not exist\n",
    "                    os.makedirs(self.templateLoc)\n",
    "                swDocSpecification = self.session.GetOpenDocSpec(\n",
    "                    self.templateLoc + \"\\\\\" + self.name\n",
    "                )\n",
    "                self.model = self.session.OpenDoc7(\n",
    "                    swDocSpecification\n",
    "                )  # OpenDoc6(self.templateLoc + '\\\\' + self.name, swConst.swDocPART, swConst.swOpenDocOptions_Silent, \"\", arg1, arg1)  #swConst.swDocumentTypes_e.swDocPART,\n",
    "            except:\n",
    "                print(\"File not found, creating new model\")\n",
    "                self.session = SWapi.win32com.client.Dispatch(\"SldWorks.Application\")\n",
    "                self.name = fileName\n",
    "                self.templateLoc = fileLocation + \"\\\\\" + self.name\n",
    "                isExist = os.path.exists(self.templateLoc)\n",
    "                print(\"templateLoc = \" + self.templateLoc)\n",
    "                print(self.templateLoc)\n",
    "                if not isExist:\n",
    "                    # Create a new directory because it does not exist\n",
    "                    os.makedirs(self.templateLoc)\n",
    "                self.model = SWapi.createNewPart(self.session, fileName, fileLocation)\n",
    "\n",
    "    def toggleVisible(self):\n",
    "        # toggles the visibility of the model\n",
    "        self.session.Visible = not self.session.Visible\n",
    "        return self.session.Visible\n",
    "\n",
    "    def getCSVfromModel(self):\n",
    "        # gets all properties and features from the model and stores them in the class + CSV files\n",
    "        getAllProperties_toCSV(self.model, self.templateLoc)  # , self.name)\n",
    "        getAllFeatures_toCSV(self.model, self.templateLoc)  # , self.name)\n",
    "        writeFeatureDefs_toCSV(self.model, self.templateLoc)  # , self.name)\n",
    "        return  # self.model\n",
    "\n",
    "    def updateModelFromCSV(self):\n",
    "        # sets all properties and features from the class/CSV to the model\n",
    "        addAllProperties_fromCSV(self.model, self.templateLoc)  # , self.name)\n",
    "        # setAllFeatures_fromCSV(self.model, self.templateLoc) #, self.name)\n",
    "\n",
    "        return\n",
    "\n",
    "    def getModelProperties(self):\n",
    "        # returns a pandas dataframe of all properties and their values\n",
    "        propertyMgr = self.model.Extension.CustomPropertyManager(\"\")\n",
    "        UseCached = False\n",
    "        vNames = SWapi.win32com.client.VARIANT(\n",
    "            pythoncom.VT_VARIANT | pythoncom.VT_BYREF, None\n",
    "        )\n",
    "        vTypes = SWapi.win32com.client.VARIANT(\n",
    "            pythoncom.VT_VARIANT | pythoncom.VT_BYREF, None\n",
    "        )\n",
    "        vValues = SWapi.win32com.client.VARIANT(\n",
    "            pythoncom.VT_VARIANT | pythoncom.VT_BYREF, None\n",
    "        )\n",
    "        resolved = SWapi.win32com.client.VARIANT(\n",
    "            pythoncom.VT_VARIANT | pythoncom.VT_BYREF, None\n",
    "        )\n",
    "        linkedProps = SWapi.win32com.client.VARIANT(\n",
    "            pythoncom.VT_VARIANT | pythoncom.VT_BYREF, None\n",
    "        )\n",
    "\n",
    "        props = propertyMgr.GetAll3(\n",
    "            vNames, vTypes, vValues, resolved, linkedProps\n",
    "        )  # GetAllCustomProperties() #\n",
    "        print(str(props))\n",
    "        for i in range(0, len(vNames.value)):\n",
    "            # print(vNames.value[i])\n",
    "            print(\n",
    "                \"  \"\n",
    "                + str(vNames.value[i])\n",
    "                + \" | \"\n",
    "                + str(vTypes.value[i])\n",
    "                + \" | \"\n",
    "                + str(vValues.value[i])\n",
    "            )\n",
    "\n",
    "\n",
    "#         # returnTypes = []\n",
    "#         # for typeVal in vTypes.value:\n",
    "#         #     print(typeVal)\n",
    "#         #     typeVal = convertPropertyType(typeVal)\n",
    "#         # allNames = propertyMgr.GetNames #(vNames, vTypes, vValues)\n",
    "#         # for name in allNames:\n",
    "#         #     print(\"  \" + str(name))\n",
    "\n",
    "#         # for i in range(0, len(vNames)):\n",
    "#         #     print(\"  \" + str(vNames[i]) + \" | \" + str(vTypes[i]) + \" | \" + str(vValues[i]))\n",
    "\n",
    "#         # value = instance.Get6(FieldName, UseCached, ValOut, ResolvedValOut, WasResolved, LinkToProperty)\n",
    "#         # propVal = ValOut\n",
    "\n",
    "#         return vNames, vTypes, vValues\n",
    "\n",
    "#     # pass\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Solidworks Functions\n",
    "Assorted functions for working with Solidworks."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "def getAllProperties_toCSV(model, saveLoc, saveName=\"Properties\"):\n",
    "    vNames, vTypes, vValues = SWapi.getAllPropertyNames(model)\n",
    "    with open(saveLoc + \"\\\\\" + saveName + \".csv\", \"w\", newline=\"\") as csvfile:\n",
    "        writer = csv.writer(\n",
    "            csvfile, delimiter=\",\", quotechar='\"', quoting=csv.QUOTE_MINIMAL\n",
    "        )\n",
    "        writer.writerow([\"Name\", \"Type\", \"Value\"])\n",
    "        for i in range(len(vNames.value)):\n",
    "            writer.writerow(\n",
    "                [\n",
    "                    str(vNames.value[i]),\n",
    "                    SWapi.convertPropertyType(vTypes.value[i]),\n",
    "                    str(vValues.value[i]),\n",
    "                ]\n",
    "            )\n",
    "\n",
    "\n",
    "def addAllProperties_fromCSV(model, saveLoc, saveName=\"Properties\"):\n",
    "    with open(saveLoc + \"\\\\\" + saveName + \".csv\", newline=\"\") as csvfile:\n",
    "        reader = csv.reader(csvfile, delimiter=\",\", quotechar='\"')\n",
    "        next(reader)\n",
    "        for row in reader:\n",
    "            # if row[0] != 'Name':\n",
    "            SWapi.addProperty(model, row[0].strip(), row[1].strip(), row[2].strip())\n",
    "\n",
    "\n",
    "def getAllFeatures_toCSV(model, saveLoc, saveName=\"Features\"):\n",
    "    allFeaturesList = SWapi.traverseFeatures(model)\n",
    "    for feature in allFeaturesList:\n",
    "        if feature.GetTypeName2 == \"ProfileFeature\":\n",
    "\n",
    "            # print()\n",
    "            # SWapi.getAllSketchDims(model, feature.Name)\n",
    "            # SWapi.selectItemByName(model, feature.Name, \"SKETCH\")\n",
    "            # SWparse.ProcessSketch(sw, model) #,feature.Name)\n",
    "\n",
    "            # selectItemByName(model, feature.Name, \"BODYFEATURE\")\n",
    "            # SWparse.ProcessExtrude(sw, model)\n",
    "            pass\n",
    "    with open(saveLoc + \"\\\\\" + saveName + \".csv\", \"w\", newline=\"\") as csvfile:\n",
    "        writer = csv.writer(\n",
    "            csvfile, delimiter=\",\", quotechar='\"', quoting=csv.QUOTE_MINIMAL\n",
    "        )\n",
    "        writer.writerow([\"ID\", \"Name\", \"Type\"])  # , 'Value'])\n",
    "        for i in range(len(allFeaturesList)):\n",
    "            writer.writerow(\n",
    "                [\n",
    "                    allFeaturesList[i].GetID,\n",
    "                    allFeaturesList[i].Name,\n",
    "                    allFeaturesList[i].GetTypeName2,\n",
    "                ]\n",
    "            )\n",
    "            # writeFeatureDefs_toCSV(model, allFeaturesList[i], saveLoc, 'Feature_Definitions.csv')\n",
    "\n",
    "            # writer.writerow([allFeaturesList[i].GetID, allFeaturesList[i].Name, allFeaturesList[i].GetTypeName2])\n",
    "            # if allFeaturesList[i].GetTypeName2 == \"RefPlane\":\n",
    "            #     if allFeaturesList[i].Name != \"Top Plane\" and allFeaturesList[i].Name != \"Front Plane\" and allFeaturesList[i].Name != \"Right Plane\":\n",
    "            #         print(\"Plane: \" + allFeaturesList[i].Name + \"  |  Type: \" + allFeaturesList[i].GetTypeName2)\n",
    "            #         planeProps = SWapi.Plane(model, allFeaturesList[i].Name, \"\", 0, units).getProperties()\n",
    "            #         refPlaneRow = ['FeatDef',{'FeatID':allFeaturesList[i].GetID}]\n",
    "            #         refPlaneRow.extend(planeProps)\n",
    "            #         writer.writerow(refPlaneRow)\n",
    "            # if allFeaturesList[i].GetTypeName2 == \"ProfileFeature\":\n",
    "            #     print(\"Sketch: \" + allFeaturesList[i].Name + \"  |  Type: \" + allFeaturesList[i].GetTypeName2)\n",
    "            #     dimList = SWapi.getAllSketchDims(model, allFeaturesList[i].Name)\n",
    "            #     for dim in dimList:\n",
    "            #         dimRow = ['DimVal', {'FeatID':allFeaturesList[i].GetID}]\n",
    "            #         dimRow.append(dim)\n",
    "            #         writer.writerow(dimRow)\n",
    "    return\n",
    "\n",
    "\n",
    "def updateFeatures_fromCSV(model, saveLoc, saveName=\"Features\"):\n",
    "    allFeaturesList = SWapi.traverseFeatures(model)\n",
    "    with open(saveLoc + \"\\\\\" + saveName + \".csv\", newline=\"\") as csvfile:\n",
    "        # Iterate through the CSV file and compare features by ID. Create new features if they don't exist.\n",
    "        reader = csv.reader(csvfile, delimiter=\",\", quotechar='\"')\n",
    "        next(reader)\n",
    "        for row in reader:\n",
    "            pass\n",
    "    pass\n",
    "\n",
    "\n",
    "def writeFeatureDefs_toCSV(model, saveLoc, saveName=\"Feature_Definitions\"):\n",
    "    allFeaturesList = SWapi.traverseFeatures(model)\n",
    "    with open(saveLoc + \"\\\\\" + saveName + \".csv\", \"w\", newline=\"\") as csvfile:\n",
    "        writer = csv.writer(\n",
    "            csvfile, delimiter=\",\", quotechar='\"', quoting=csv.QUOTE_MINIMAL\n",
    "        )\n",
    "        writer.writerow([\"FeatID\", \"DimName\", \"DimVal\"])\n",
    "    for i in range(len(allFeaturesList)):\n",
    "        featDict = allFeaturesList[i]\n",
    "        featType = featDict.GetTypeName2\n",
    "        if featType == \"RefPlane\":\n",
    "            if (\n",
    "                featDict.Name != \"Top Plane\"\n",
    "                and featDict.Name != \"Front Plane\"\n",
    "                and featDict.Name != \"Right Plane\"\n",
    "            ):\n",
    "                planeProps = SWapi.Plane(\n",
    "                    model, featDict.Name, \"\", 0, units\n",
    "                ).getProperties()\n",
    "                print(planeProps)\n",
    "                if not planeProps == None:\n",
    "                    refPlaneRow = [featDict.GetID]\n",
    "                    refPlaneRow.extend(planeProps)\n",
    "                    with open(\n",
    "                        saveLoc + \"\\\\\" + saveName + \".csv\", \"a\", newline=\"\"\n",
    "                    ) as csvfile:\n",
    "                        writer = csv.writer(\n",
    "                            csvfile,\n",
    "                            delimiter=\",\",\n",
    "                            quotechar='\"',\n",
    "                            quoting=csv.QUOTE_MINIMAL,\n",
    "                        )\n",
    "                        writer.writerow(refPlaneRow)\n",
    "        if featType == \"ProfileFeature\":\n",
    "            dimList = SWapi.getAllSketchDims(model, featDict.Name)\n",
    "            for dim in dimList:\n",
    "                dimRow = [featDict.GetID]\n",
    "                dimRow.append(dim)\n",
    "                with open(\n",
    "                    saveLoc + \"\\\\\" + saveName + \".csv\", \"a\", newline=\"\"\n",
    "                ) as csvfile:\n",
    "                    writer = csv.writer(\n",
    "                        csvfile, delimiter=\",\", quotechar='\"', quoting=csv.QUOTE_MINIMAL\n",
    "                    )\n",
    "                    writer.writerow(dimRow)\n",
    "                # writer.writerow(dimRow)\n",
    "        if featType == \"ICE\":\n",
    "            print(\"ICE\")\n",
    "\n",
    "    return\n",
    "\n",
    "\n",
    "def writeGenericFeatDefs_toCSV(model, saveLoc, saveName=\"Feature_Defs\"):\n",
    "    allFeaturesList = SWapi.traverseFeatures(model)\n",
    "    with open(saveLoc + \"\\\\\" + saveName + \".csv\", \"w\", newline=\"\") as csvfile:\n",
    "        writer = csv.writer(\n",
    "            csvfile, delimiter=\",\", quotechar='\"', quoting=csv.QUOTE_MINIMAL\n",
    "        )\n",
    "        writer.writerow([\"Feature Type\", \"FeatID\", \"DimName\", \"DimVal\"])\n",
    "\n",
    "    for i in range(len(allFeaturesList)):\n",
    "        rowData = []\n",
    "        featDict = allFeaturesList[i]\n",
    "        featType = featDict.GetTypeName2\n",
    "        rowData.append(featType)\n",
    "        featID = featDict.GetID\n",
    "        rowData.append(featID)\n",
    "        print(\"Feature ID: \" + str(featID) + \"  |  Feature Type: \" + str(featType))\n",
    "        feature = model.FeatureByID(featID)\n",
    "        print(str(feature))\n",
    "        if feature.getDefinition != None:  # SWapi.varNone:\n",
    "            defList = feature.getDefinition\n",
    "            print(defList)\n",
    "            for defItem in defList:\n",
    "                print(str(defItem))\n",
    "                rowData.append(defItem)\n",
    "            with open(saveLoc + \"\\\\\" + saveName + \".csv\", \"a\", newline=\"\") as csvfile:\n",
    "                writer = csv.writer(\n",
    "                    csvfile, delimiter=\",\", quotechar='\"', quoting=csv.QUOTE_MINIMAL\n",
    "                )\n",
    "                writer.writerow(rowData)\n",
    "\n",
    "    return\n",
    "\n",
    "\n",
    "# def getAllFeatures_fromExcel(fileDataSaveLoc, fileFeaturesSaveName):\n",
    "#     swTemplate_name = fileDataSaveLoc + \"\\\\\" + fileFeaturesSaveName\n",
    "#     xlTemplate = xl.xw.Book(swTemplate_name)\n",
    "#     propSheet = xlTemplate.sheets[\"FileProperties\"]\n",
    "#     featSheet = xlTemplate.sheets[\"PartFeatures\"]\n",
    "#     planeSheet = xlTemplate.sheets[\"PartPlanes\"]\n",
    "#     sketchSheet = xlTemplate.sheets[\"PartSketches\"]\n",
    "#     fileProps = xl.getDF_fromSheet(propSheet)\n",
    "#     print(fileProps)\n",
    "#     allFeatures = xl.getDF_fromSheet(featSheet)\n",
    "#     planes = xl.getDF_fromSheet(planeSheet, \"B1\")\n",
    "#     print(planes)\n",
    "#     sketches = xl.getDF_fromSheet(sketchSheet)\n",
    "# def getAllFeatures_fromExcel(fileDataSaveLoc, fileFeaturesSaveName):\n",
    "#     swTemplate_name = fileDataSaveLoc + \"\\\\\" + fileFeaturesSaveName\n",
    "#     xlTemplate = xl.xw.Book(swTemplate_name)\n",
    "#     propSheet = xlTemplate.sheets[\"FileProperties\"]\n",
    "#     featSheet = xlTemplate.sheets[\"PartFeatures\"]\n",
    "#     planeSheet = xlTemplate.sheets[\"PartPlanes\"]\n",
    "#     sketchSheet = xlTemplate.sheets[\"PartSketches\"]\n",
    "#     fileProps = xl.getDF_fromSheet(propSheet)\n",
    "#     print(fileProps)\n",
    "#     allFeatures = xl.getDF_fromSheet(featSheet)\n",
    "#     planes = xl.getDF_fromSheet(planeSheet, \"B1\")\n",
    "#     print(planes)\n",
    "#     sketches = xl.getDF_fromSheet(sketchSheet)\n",
    "\n",
    "#     return fileProps, allFeatures, planes, sketches\n",
    "#     return fileProps, allFeatures, planes, sketches\n",
    "\n",
    "\n",
    "def getAllFeature_toExcel(model, fileDataSaveLoc, fileFeaturesSaveName):\n",
    "    return\n",
    "\n",
    "\n",
    "def updateFeatures_fromExcel(model, fileDataSaveLoc, fileFeaturesSaveName):\n",
    "\n",
    "    return\n",
    "\n",
    "\n",
    "# def newPart_init(partName, csvFolderSaveLoc=CSVtemplateSaveLoc):\n",
    "#     # Create new part templates and save them to the specified location.\n",
    "#     # If no location is specified, save inside a new folder in the default location.\n",
    "\n",
    "#     # copy and rename the template folder to the new part name:\n",
    "#     if not os.path.exists(csvFolderSaveLoc + \"\\\\\" + partName):\n",
    "#         shutil.copytree(CSVtemplateSaveLoc, csvFolderSaveLoc + \"\\\\\" + partName)\n",
    "#         os.rename(\n",
    "#             csvFolderSaveLoc + \"\\\\\" + partName, csvFolderSaveLoc + \"\\\\\" + partName\n",
    "#         )\n",
    "#     # copy and rename the template folder to the new part name:\n",
    "#     if not os.path.exists(csvFolderSaveLoc + \"\\\\\" + partName):\n",
    "#         shutil.copytree(CSVtemplateSaveLoc, csvFolderSaveLoc + \"\\\\\" + partName)\n",
    "#         os.rename(\n",
    "#             csvFolderSaveLoc + \"\\\\\" + partName, csvFolderSaveLoc + \"\\\\\" + partName\n",
    "#         )\n",
    "\n",
    "#     return\n",
    "#     return\n",
    "\n",
    "# \"\"\"\n",
    "# insertPartName = \"testCircDesk\"  # .SLDPRT'\n",
    "# insertPartLoc = r\"C:\\Users\\alaureijs\\Local Projects\\Solidworks\"\n",
    "\n",
    "# fileDataSaveLoc = r\"G:\\My Drive\\Google Drive - Projects\\Code\\NoteDB\"\n",
    "# fileDataSaveLoc = (\n",
    "#     r\"C:\\Users\\alaureijs\\OneDrive - moorecoinc\\Projects\\Automation\\Solidworks\"\n",
    "# )\n",
    "# fileFeaturesSaveName = \"SW Part Template.csv\"  # xlsm'\n",
    "# partTemplateFolder = (\n",
    "#     r\"G:\\My Drive\\Google Drive - Work\\MooreCo\\swAPI\"  # \\SW_Part_Template\n",
    "# )\n",
    "\n",
    "# # model = sw.ActiveDoc #SWapi.createNewPart(sw, insertPartName, insertPartLoc)\n",
    "\n",
    "\n",
    "# testModel = Model()  # activeDocName, activeDocLoc)\n",
    "# print(testModel.name)\n",
    "# print(testModel.templateLoc)\n",
    "# print(testModel.model)\n",
    "# print(testModel.session)\n",
    "# # testModel.getCSVfromModel()\n",
    "# # testModel.getModelProperties()\n",
    "# testModel.updateModelFromCSV()\n",
    "# testModel = Model()  # activeDocName, activeDocLoc)\n",
    "# print(testModel.name)\n",
    "# print(testModel.templateLoc)\n",
    "# print(testModel.model)\n",
    "# print(testModel.session)\n",
    "# # testModel.getCSVfromModel()\n",
    "# # testModel.getModelProperties()\n",
    "# testModel.updateModelFromCSV()\n",
    "# testModel.getCSVfromModel()\n",
    "# writeGenericFeatDefs_toCSV(testModel.model, testModel.templateLoc, \"Generic_Feat_Defs\")\n",
    "#  \"\"\"\n",
    "\n",
    "# # fileProps, allFeatures, planes, sketches = getAllFeatures_fromExcel(fileDataSaveLoc, fileFeaturesSaveName)\n",
    "\n",
    "# # print(\"Props\")\n",
    "# # print(fileProps)\n",
    "# # print(\"Feats\")\n",
    "# # print( allFeatures)\n",
    "# # print(\"planes\")\n",
    "# # print( planes)\n",
    "# # print(\"sketches\")\n",
    "# # print( sketches)\n",
    "\n",
    "# # getAllProperties_toCSV(model, workCSVdataSaveLoc, fileFeaturesSaveName)\n",
    "\n",
    "\n",
    "# ##\n",
    "# # getAllFeatures_toCSV(model, workCSVdataSaveLoc, fileFeaturesSaveName)\n",
    "# ##\n",
    "\n",
    "# # features = SWapi.traverseFeatures(model)\n",
    "\n",
    "# # print(features)\n",
    "\n",
    "# # SWapi.GetAllDimensions(features)\n",
    "\n",
    "# print(\"\\n\\nDone.\")\n",
    "# print(\"\\n\\nDone.\")\n",
    "\n",
    "\n",
    "def createPlanes(model, planeProps, units, edit=False):\n",
    "    # print(planeProps)\n",
    "    print(\"Creating planes...\")\n",
    "    print(len(planeProps))\n",
    "    for i in range(len(planeProps)):\n",
    "        print(i)\n",
    "        # i=i-1\n",
    "        lookupval = i\n",
    "        lookupval = planeProps.iloc[:, :0].iloc[lookupval].name\n",
    "        print(lookupval)\n",
    "        planeName = lookupval  # planeProps.loc[lookupval, 'PlaneName']\n",
    "        print(\"  \" + planeName)\n",
    "\n",
    "        # planeName = planeProps.loc[lookupval, 'PlaneName']\n",
    "        # print(\"  \" + planeName)\n",
    "        planeOffsetFrom = planeProps.loc[lookupval, \"OffsetFrom\"]\n",
    "        print(\"  \" + planeOffsetFrom)\n",
    "        planeOffsetDist = planeProps.loc[lookupval, \"OffsetDistance\"]\n",
    "        print(\"  \" + str(planeOffsetDist))\n",
    "\n",
    "        # planeType = planeProps['Type'][i]\n",
    "        plane = SWapi.Plane(model, planeName, planeOffsetFrom, planeOffsetDist, units)\n",
    "        if edit == True:\n",
    "            plane.edit()\n",
    "            print(\n",
    "                f\"Edited '{planeName}' to '{planeOffsetDist}' {units} from '{planeOffsetFrom}'\"\n",
    "            )\n",
    "        else:\n",
    "            plane.create()\n",
    "            print(\n",
    "                f\"Created '{planeName}' @'{planeOffsetDist}' {units} from '{planeOffsetFrom}'\"\n",
    "            )\n",
    "    return\n",
    "\n",
    "\n",
    "# # print(fileProps.loc['Units', 'Value'])\n",
    "# # units = str(fileProps.loc['Units', 'Value'])\n",
    "# # #print(planes)\n",
    "\n",
    "# # createPlanes(model, planes, units) #, edit=True)\n",
    "\n",
    "\n",
    "# def createRandomSkeleton():\n",
    "#     planesToCreate = [5, 10, 15, 20, 25, 30]\n",
    "#     planeToOffset = [\"Right Plane\", \"Front Plane\", \"Top Plane\"]\n",
    "#     constraintDirection = [\"Horizontal\", \"Vertical\"]\n",
    "#     for plane in planesToCreate:\n",
    "#         planeName = \"OffsetPlane_\" + str(plane)\n",
    "#         insertPlane = SWapi.Plane(\n",
    "#             model, planeName, random.choice(planeToOffset), plane, units\n",
    "#         )\n",
    "#         insertPlane.create()\n",
    "#         sketchToCreate = SWapi.Sketch(\n",
    "#             model, \"Sketch_\" + planeName, insertPlane.refPlane\n",
    "#         )\n",
    "#         sketchToCreate.create()\n",
    "#         # print(sketchToCreate.name)\n",
    "#         # SWapi.clearSelections(model)\n",
    "#         print(\"Created \" + sketchToCreate.name + \" on \" + insertPlane.refPlane)\n",
    "#         line1 = SWapi.Line(model, sketchToCreate.name, \"Line_Test\" + str(plane))\n",
    "#         print(\"creating line: \" + line1.name)\n",
    "#         lineConstraint = random.choice(constraintDirection)\n",
    "#         lineDist = random.choice(planesToCreate)\n",
    "#         print(\n",
    "#             \"Line constraint: \" + lineConstraint + \"  |  Line length: \" + str(lineDist)\n",
    "#         )\n",
    "#         line = line1.create(lineConstraint, lineDist, \"mm\")\n",
    "# def createRandomSkeleton():\n",
    "#     planesToCreate = [5, 10, 15, 20, 25, 30]\n",
    "#     planeToOffset = [\"Right Plane\", \"Front Plane\", \"Top Plane\"]\n",
    "#     constraintDirection = [\"Horizontal\", \"Vertical\"]\n",
    "#     for plane in planesToCreate:\n",
    "#         planeName = \"OffsetPlane_\" + str(plane)\n",
    "#         insertPlane = SWapi.Plane(\n",
    "#             model, planeName, random.choice(planeToOffset), plane, units\n",
    "#         )\n",
    "#         insertPlane.create()\n",
    "#         sketchToCreate = SWapi.Sketch(\n",
    "#             model, \"Sketch_\" + planeName, insertPlane.refPlane\n",
    "#         )\n",
    "#         sketchToCreate.create()\n",
    "#         # print(sketchToCreate.name)\n",
    "#         # SWapi.clearSelections(model)\n",
    "#         print(\"Created \" + sketchToCreate.name + \" on \" + insertPlane.refPlane)\n",
    "#         line1 = SWapi.Line(model, sketchToCreate.name, \"Line_Test\" + str(plane))\n",
    "#         print(\"creating line: \" + line1.name)\n",
    "#         lineConstraint = random.choice(constraintDirection)\n",
    "#         lineDist = random.choice(planesToCreate)\n",
    "#         print(\n",
    "#             \"Line constraint: \" + lineConstraint + \"  |  Line length: \" + str(lineDist)\n",
    "#         )\n",
    "#         line = line1.create(lineConstraint, lineDist, \"mm\")\n",
    "\n",
    "\n",
    "# # drw1 = SWapi.DRW(sw)\n",
    "# # drw1.create()\n",
    "# # createRandomSkeleton()\n",
    "\n",
    "# # skeletonPart = SWapi.insertPart(model, insertPartLoc + \"\\\\\" + insertPartName + \".SLDPRT\")\n",
    "\n",
    "\n",
    "# # featureList = ['Overall_Footprint_Worksurface', 'Worksurface_Sketch', ]\n",
    "\n",
    "\n",
    "# # Ignore full feature extraction for now. Just build parts from planes/sketches with named dimensions.\n",
    "# # Then extract any named dimensions from all features and save/update them to/from a CSV file.\n",
    "\n",
    "# # File should be pulled from a skeleton TDD sketch file anyway, then parts are just a series of extrudes.\n",
    "\n",
    "# # Things to figure out:\n",
    "# #   Midpoint relations\n",
    "# #   Extrudes\n",
    "# #   Revolves\n",
    "# #   Cuts\n",
    "# #   Create Drawing\n",
    "# #   Create Assembly\n",
    "# #   Import checked dimensions to drawing\n",
    "\n",
    "\n",
    "# # OffsetPlane1 = SWapi.Plane(model, \"OffsetPlane_1\", \"Right Plane\", 10, units)\n",
    "# # #TopPlane = SWapi.Plane(model, \"TopPlane_Copy\", \"Top Plane\", 0, units)\n",
    "# # #OffsetPlane1.create()\n",
    "\n",
    "# # print(OffsetPlane1.offsetDistance)\n",
    "# # print(OffsetPlane1.refPlane)\n",
    "# # #OffsetPlane1.offsetDistance = 20\n",
    "\n",
    "# # OffsetPlane1.getProperties()\n",
    "# # print(OffsetPlane1.offsetDistance)\n",
    "# # print(OffsetPlane1.refPlane)\n",
    "\n",
    "# # SWapi.create_RefAxis(model, \"OffsetPlane_1\", \"Front Plane\")\n",
    "# # SWapi.clearSelections\n",
    "# # sketch1 = SWapi.Sketch(model, \"TestSketch\", \"OffsetPlane_1\").create()\n",
    "\n",
    "# # addAllProperties_fromCSV(model, fileDataSaveLoc, filePropertySaveName)\n",
    "# # getAllProperties_toCSV(model, fileDataSaveLoc, filePropertySaveName)\n",
    "# # getAllFeatures_toCSV(model, fileDataSaveLoc, fileFeaturesSaveName)\n",
    "\n",
    "# # dimlist = SWapi.getAllSketchDims(model, \"Sketch1\")\n",
    "\n",
    "# # propertyToAdd = [['TestProp1', 'Date', \"4-13-59\"],['TestProp2', 'Number', 666],['TestProp3', 'Text','This is a test']]\n",
    "# # for prop in propertyToAdd:\n",
    "# #     SWapi.addProperty(model, prop[0], prop[1], prop[2])\n",
    "\n",
    "# # SWapi.getSelectedItem(model)\n",
    "\n",
    "# # SWapi.createPlane_OffsetDistance(model, \"Front Plane\", 10, units)\n",
    "# # vNames, vTypes, vValues = SWapi.getAllPropertyNames(model)\n",
    "\n",
    "# # for i in range(len(vNames.value)):\n",
    "# #     print(\"  \" + str(vNames.value[i]) + \" | \" + SWapi.convertPropertyType(vTypes.value[i]) + \" | \" + str(vValues.value[i]))\n",
    "\n",
    "# # for name in vNames:\n",
    "# #     print(str(name.value, ))\n",
    "# #     print(SWapi.getPropertyVal_byName(model, name))\n",
    "# #     #print(SWapi.getPropertyType(model, name))\n",
    "# #     #print(SWapi.getPropertyDescription(model, name))\n",
    "\n",
    "\n",
    "# # #SWapi.traverseFeatures(model)\n",
    "# # selected1 = SWapi.selectPlaneByName(model, \"Front Plane\")\n",
    "# # newSketch = SWapi.addSketch(model) #, \"Front Plane\")\n",
    "# # #print(newSketch)\n",
    "# # SWapi.toggleDimInputBox(sw, False)\n",
    "# # newCircle = SWapi.sketchCircle(newSketch, 0, 0, 0, circle1_radius, units)\n",
    "# # SWapi.addDimension(model, circle1_radius*1.5, circle1_radius*1.5, circle2_radius*1.5, units)\n",
    "# # model = SWapi.clearSelections(model)\n",
    "\n",
    "# # model2 = sw.ActiveDoc\n",
    "\n",
    "# # selected = SWapi.selectPlaneByName(model2, \"Right Plane\")\n",
    "# # print(selected.Name)\n",
    "# # newSketch2 = SWapi.addSketch(model2) #, \"Right Plane\")\n",
    "# # newCircle2 = SWapi.sketchCircle(newSketch2, 2, 2, 2, circle2_radius, units)\n",
    "# # SWapi.addDimension(model2, circle2_radius*1.5, circle2_radius*1.5, circle2_radius*1.5, units)\n",
    "# # newCircle2 = SWapi.sketchCircle(newSketch2, 0, 5, 0, circle2_radius+1, units)\n",
    "# # SWapi.addDimension(model2, circle2_radius*1.5, circle2_radius*1.5, circle2_radius*1.5, units)\n",
    "\n",
    "# # model2 = SWapi.clearSelections(model2)\n",
    "# # SWapi.toggleDimInputBox(sw, True)\n",
    "# # #model2 = SWapi.clearSelections(model2)\n",
    "# # # model = sw.model\n",
    "# # #selMgr = model.SelectionManager\n",
    "# # #print(type(selMgr))\n",
    "# # #aSketch = selMgr.GetSelectedObject(1) #.GetSpecificFeature2\n",
    "# # #aSketch.Name"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 2
}
